version: 2

defaults: &defaults
  working_directory: ~/app
  docker:
    - image: node:11

jobs:
  prepare:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - persist_to_workspace:
          root: ~/app
          paths: .
  test:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/app
      - run: npm run test
  build:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/app
      - run: npm run build
      - persist_to_workspace:
          root: ~/app
          paths:
            - dist
  deploy:
    <<: *defaults
    dependencies:
      pre:
        - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
    steps:
      - attach_workspace:
          at: ~/app
      - run:
          name: Publish package
          command: npm publish

workflows:
  version: 2
  main:
    jobs:
      - prepare:
          filters:
            tags:
              only: /.*/
      - build:
          requires:
            - prepare
          filters:
            tags:
              only: /.*/
      - test:
          requires:
            - prepare
          filters:
            tags:
              only: /.*/
      - test:
          filters:
            tags:
              only: /^v.*/
      - deploy:
          requires:
            - build
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
